// AUTO-GENERATED by scripts/generate-exercise-index.ts
// Do not edit manually - regenerate using: npm run generate-exercise-index

// ========== ENGLISH INDEXES ==========
export const EXERCISE_INDEX_FULL_EN = `**Available Exercises Database:**

**Shoulders** (8 shown):
  - Dumbbell Lateral Raise
  - Military Press (AKA Overhead Press)
  - Seated Arnold Press
  - Seated Shoulder Press
  - Cable Face Pull
  - Cable Reverse Fly
  - Cable Lateral Raise
  - Band Pull Apart

**Upper Arms** (12 shown):
  - Standing Hammer Curl
  - Standing Dumbbell Curl
  - Standing Barbell Curl
  - EZ Bar Curl
  - Seated Dumbbell Curl
  - One-Arm Prone Incline Dumbbell Curl
  - Chest-Supported Incline Dumbbell Curl
  - Rope Tricep Extension
  - French Press
  - Bench Dip
  - One-Arm Cable Tricep Extension
  - Standing Low Pulley Overhead Tricep Extension (Rope Extension)

**Forearms** (2 shown):
  - Dumbbell Wrist Curl
  - Dumbbell Wrist Rotation

**Chest** (8 shown):
  - Dumbbell Bench Press
  - Incline Dumbbell Bench Press
  - Barbell Bench Press
  - Standing Cable Fly
  - Hammer Strength Bench Press
  - Incline Dumbbell Flys
  - Standing Low to High Cable Fly
  - Push Up

**Abdomen** (11 shown):
  - Hanging Leg Raise
  - Plank
  - Sit Up
  - Abdominal Air Bike (AKA Bicycle)
  - Dead Bug
  - Lying Leg Raise With Hip Thrust
  - Hollow Body Crunch with Arm Sweep
  - Plank to Push-Up
  - Side Plank with Hip Dip
  - Side Plank with Rotational Reach-Through
  - Renegade Row

**Upper Back** (10 shown):
  - Bent Over Row
  - Seated Cable Row
  - Tripod Dumbbell Row
  - Reverse Grip Bent Over Row
  - Inverted Row
  - High Standing Banded Row
  - Seated Floor Single-Arm Cable Lat Pulldown
  - Lat Pull Down
  - Pull Up
  - Rope Straight Arm Pull Down

**Lower Back** (2 shown):
  - Superman Raise
  - Prone Swimmer Raises

**Glutes** (6 shown):
  - Hyperextension
  - Bodyweight Glute Bridge
  - Barbell Glute Bridge
  - Side Lying Hip Abduction
  - Modified Side Plank Hip Abduction
  - Single-Leg Hip Thrust

**Upper Legs** (12 shown):
  - Barbell Back Squat
  - Leg Extension
  - Leg Press
  - Bodyweight Lunge
  - Single Leg Squat From Bench
  - Bodyweight Bulgarian Split Squat
  - Bodyweight Squat
  - Assisted Pistol Squat
  - Conventional Deadlift
  - Romanian Deadlift (AKA RDL)
  - Nordic Hamstring Curl
  - Straight Leg Deadlift

**Lower Legs** (3 shown):
  - Bodyweight Standing Calf Raise
  - One-Leg Standing Bodyweight Calf Raise
  - Unilateral Eccentric Bodyweight Standing Calf Raise

**Warmup** (8 shown):
  - Rowing Machine
  - Stationary Bike
  - Treadmill Walk/Jog (5° Incline)
  - Bodyweight Squat
  - Pelvic Tilt
  - Jogging in Place
  - Wall Push-Ups
  - Arm Circles

**Cardio** (8 shown):
  - Zone 2 Running - Outdoor
  - 4x4 Interval Running - Outdoor
  - Zone 2 Running - Indoor Treadmill
  - 4x4 Interval Running - Indoor Treadmill
  - Zone 2 Cycling - Outdoor
  - 4x4 Interval Cycling - Outdoor
  - Zone 2 Cycling - Indoor Stationary Bike
  - 4x4 Interval Cycling - Indoor Stationary Bike


**Usage:**
- Reference specific exercise names when making recommendations
- Use <<EXERCISE_QUERY:bodypart:exercise_name>> to display exercise card
- Example: "Try **External Rotation** <<EXERCISE_QUERY:Shoulders:external rotation>>"
`;

export const EXERCISE_INDEX_COMPACT_EN = `**Exercise Database** (reference for specific recommendations):
• Shoulders: Dumbbell Lateral Raise, Military Press (AKA Overhead Press), Seated Arnold Press, Seated Shoulder Press, Cable Face Pull, Cable Reverse Fly, Cable Lateral Raise, Band Pull Apart, Cable External Rotation, Banded Lateral Raise, Cable Internal Rotation, Standing Banded Face Pull...
• Upper Arms: Standing Hammer Curl, Standing Dumbbell Curl, Standing Barbell Curl, EZ Bar Curl, Seated Dumbbell Curl, One-Arm Prone Incline Dumbbell Curl, Chest-Supported Incline Dumbbell Curl, Rope Tricep Extension, French Press, Bench Dip, One-Arm Cable Tricep Extension, Standing Low Pulley Overhead Tricep Extension (Rope Extension), Dumbbell Tricep Extension...
• Forearms: Dumbbell Wrist Curl, Dumbbell Wrist Rotation...
• Chest: Dumbbell Bench Press, Incline Dumbbell Bench Press, Barbell Bench Press, Standing Cable Fly, Hammer Strength Bench Press, Incline Dumbbell Flys, Standing Low to High Cable Fly, Push Up, Standing High to Low Cable Fly...
• Abdomen: Hanging Leg Raise, Plank, Sit Up, Abdominal Air Bike (AKA Bicycle), Dead Bug, Lying Leg Raise With Hip Thrust, Hollow Body Crunch with Arm Sweep, Plank to Push-Up, Spiderman Plank, Mountain Climbers, Side Plank with Hip Dip, Side Plank with Rotational Reach-Through, Renegade Row...
• Upper Back: Bent Over Row, Seated Cable Row, Tripod Dumbbell Row, Reverse Grip Bent Over Row, Inverted Row, High Standing Banded Row, Seated Floor Single-Arm Cable Lat Pulldown, Lat Pull Down, Pull Up, Rope Straight Arm Pull Down...
• Lower Back: Superman Raise, Prone Swimmer Raises...
• Glutes: Hyperextension, Bodyweight Glute Bridge, Barbell Glute Bridge, Side Lying Hip Abduction, Modified Side Plank Hip Abduction, Single-Leg Hip Thrust...
• Upper Legs: Barbell Back Squat, Leg Extension, Leg Press, Bodyweight Lunge, Single Leg Squat From Bench, Bodyweight Bulgarian Split Squat, Bodyweight Squat, Assisted Pistol Squat, Single-Leg Box Squat (Sit-to-Stand), Wall Sit (Isometric Hold), Burpee, Conventional Deadlift, Romanian Deadlift (AKA RDL), Nordic Hamstring Curl, Straight Leg Deadlift...
• Lower Legs: Bodyweight Standing Calf Raise, One-Leg Standing Bodyweight Calf Raise, Unilateral Eccentric Bodyweight Standing Calf Raise...
• Warmup: Rowing Machine, Stationary Bike, Treadmill Walk/Jog (5° Incline), Bodyweight Squat, Pelvic Tilt, Jogging in Place, Wall Push-Ups, Arm Circles, Standing Trunk Rotation, Elliptical Machine, Jump Rope...
• Cardio: Zone 2 Running - Outdoor, 4x4 Interval Running - Outdoor, Zone 2 Running - Indoor Treadmill, 4x4 Interval Running - Indoor Treadmill, Zone 2 Cycling - Outdoor, 4x4 Interval Cycling - Outdoor, Zone 2 Cycling - Indoor Stationary Bike, 4x4 Interval Cycling - Indoor Stationary Bike, Zone 2 Rowing, 4x4 Interval Rowing...
`;

export const EXERCISE_INDEX_RAW_EN = {
  "Shoulders": {
    "total": 19,
    "exercises": [
      "Dumbbell Lateral Raise",
      "Military Press (AKA Overhead Press)",
      "Seated Arnold Press",
      "Seated Shoulder Press",
      "Cable Face Pull",
      "Cable Reverse Fly",
      "Cable Lateral Raise",
      "Band Pull Apart",
      "Cable External Rotation",
      "Banded Lateral Raise",
      "Cable Internal Rotation",
      "Standing Banded Face Pull",
      "Single Arm Banded External Rotation",
      "Neutral Grip Dumbbell Front Raise",
      "Arc Shoulder Raise",
      "Modified Banded Lateral Raise",
      "Banded Shoulder Flexion Raise",
      "Straight-Arm Banded Shoulder Flexion Raise",
      "Side-Lying Shoulder External Rotation"
    ],
    "equipment": [
      "Dumbbell",
      "Barbell",
      "Cable",
      "Bands",
      "Machine"
    ],
    "difficulties": [
      "beginner",
      "intermediate"
    ]
  },
  "Upper Arms (Biceps)": {
    "total": 7,
    "exercises": [
      "Standing Hammer Curl",
      "Standing Dumbbell Curl",
      "Standing Barbell Curl",
      "EZ Bar Curl",
      "Seated Dumbbell Curl",
      "One-Arm Prone Incline Dumbbell Curl",
      "Chest-Supported Incline Dumbbell Curl"
    ],
    "equipment": [
      "Dumbbell",
      "Barbell",
      "Bench"
    ],
    "difficulties": [
      "beginner"
    ]
  },
  "Upper Arms (Triceps)": {
    "total": 6,
    "exercises": [
      "Rope Tricep Extension",
      "French Press",
      "Bench Dip",
      "One-Arm Cable Tricep Extension",
      "Standing Low Pulley Overhead Tricep Extension (Rope Extension)",
      "Dumbbell Tricep Extension"
    ],
    "equipment": [
      "Cable",
      "Barbell",
      "Bodyweight",
      "Dumbbell",
      "Bench"
    ],
    "difficulties": [
      "beginner"
    ]
  },
  "Forearms": {
    "total": 2,
    "exercises": [
      "Dumbbell Wrist Curl",
      "Dumbbell Wrist Rotation"
    ],
    "equipment": [
      "Dumbbell",
      "Bench"
    ],
    "difficulties": [
      "beginner"
    ]
  },
  "Chest": {
    "total": 9,
    "exercises": [
      "Dumbbell Bench Press",
      "Incline Dumbbell Bench Press",
      "Barbell Bench Press",
      "Standing Cable Fly",
      "Hammer Strength Bench Press",
      "Incline Dumbbell Flys",
      "Standing Low to High Cable Fly",
      "Push Up",
      "Standing High to Low Cable Fly"
    ],
    "equipment": [
      "Dumbbell",
      "Barbell",
      "Cable",
      "Machine",
      "Bodyweight"
    ],
    "difficulties": [
      "beginner",
      "intermediate"
    ]
  },
  "Abdomen (Abs)": {
    "total": 10,
    "exercises": [
      "Hanging Leg Raise",
      "Plank",
      "Sit Up",
      "Abdominal Air Bike (AKA Bicycle)",
      "Dead Bug",
      "Lying Leg Raise With Hip Thrust",
      "Hollow Body Crunch with Arm Sweep",
      "Plank to Push-Up",
      "Spiderman Plank",
      "Mountain Climbers"
    ],
    "equipment": [
      "Bodyweight"
    ],
    "difficulties": [
      "advanced",
      "beginner",
      "intermediate"
    ]
  },
  "Abdomen (Obliques)": {
    "total": 3,
    "exercises": [
      "Side Plank with Hip Dip",
      "Side Plank with Rotational Reach-Through",
      "Renegade Row"
    ],
    "equipment": [
      "Bodyweight",
      "Dumbbell"
    ],
    "difficulties": [
      "beginner",
      "intermediate"
    ]
  },
  "Upper Back": {
    "total": 7,
    "exercises": [
      "Bent Over Row",
      "Seated Cable Row",
      "Tripod Dumbbell Row",
      "Reverse Grip Bent Over Row",
      "Inverted Row",
      "High Standing Banded Row",
      "Seated Floor Single-Arm Cable Lat Pulldown"
    ],
    "equipment": [
      "Barbell",
      "Cable",
      "Dumbbell",
      "Bodyweight",
      "Smith Machine",
      "TRX",
      "Rings",
      "Bands"
    ],
    "difficulties": [
      "beginner",
      "intermediate"
    ]
  },
  "Upper Back (Lats)": {
    "total": 3,
    "exercises": [
      "Lat Pull Down",
      "Pull Up",
      "Rope Straight Arm Pull Down"
    ],
    "equipment": [
      "Cable",
      "Bodyweight"
    ],
    "difficulties": [
      "beginner"
    ]
  },
  "Lower Back": {
    "total": 2,
    "exercises": [
      "Superman Raise",
      "Prone Swimmer Raises"
    ],
    "equipment": [
      "Bodyweight"
    ],
    "difficulties": [
      "beginner"
    ]
  },
  "Glutes": {
    "total": 6,
    "exercises": [
      "Hyperextension",
      "Bodyweight Glute Bridge",
      "Barbell Glute Bridge",
      "Side Lying Hip Abduction",
      "Modified Side Plank Hip Abduction",
      "Single-Leg Hip Thrust"
    ],
    "equipment": [
      "Bodyweight",
      "Barbell",
      "Bench"
    ],
    "difficulties": [
      "beginner",
      "intermediate"
    ]
  },
  "Upper Legs (Quads)": {
    "total": 11,
    "exercises": [
      "Barbell Back Squat",
      "Leg Extension",
      "Leg Press",
      "Bodyweight Lunge",
      "Single Leg Squat From Bench",
      "Bodyweight Bulgarian Split Squat",
      "Bodyweight Squat",
      "Assisted Pistol Squat",
      "Single-Leg Box Squat (Sit-to-Stand)",
      "Wall Sit (Isometric Hold)",
      "Burpee"
    ],
    "equipment": [
      "Barbell",
      "Machine",
      "Bodyweight",
      "Bench",
      "TRX",
      "Bands"
    ],
    "difficulties": [
      "intermediate",
      "beginner"
    ]
  },
  "Upper Legs (Hamstrings)": {
    "total": 5,
    "exercises": [
      "Conventional Deadlift",
      "Romanian Deadlift (AKA RDL)",
      "Nordic Hamstring Curl",
      "Straight Leg Deadlift",
      "Single-Leg Romanian Deadlift"
    ],
    "equipment": [
      "Barbell",
      "Bodyweight",
      "Kettlebell",
      "Dumbbell",
      "Weight Plate"
    ],
    "difficulties": [
      "intermediate",
      "beginner",
      "advanced"
    ]
  },
  "Lower Legs (Calves)": {
    "total": 3,
    "exercises": [
      "Bodyweight Standing Calf Raise",
      "One-Leg Standing Bodyweight Calf Raise",
      "Unilateral Eccentric Bodyweight Standing Calf Raise"
    ],
    "equipment": [
      "Bodyweight"
    ],
    "difficulties": [
      "beginner",
      "intermediate"
    ]
  },
  "Warmup": {
    "total": 11,
    "exercises": [
      "Rowing Machine",
      "Stationary Bike",
      "Treadmill Walk/Jog (5° Incline)",
      "Bodyweight Squat",
      "Pelvic Tilt",
      "Jogging in Place",
      "Wall Push-Ups",
      "Arm Circles",
      "Standing Trunk Rotation",
      "Elliptical Machine",
      "Jump Rope"
    ],
    "equipment": [
      "Rowing Machine",
      "Stationary Bike",
      "Treadmill",
      "Bodyweight",
      "Elliptical Machine",
      "Jump Rope"
    ],
    "difficulties": [
      "beginner"
    ]
  },
  "Cardio": {
    "total": 10,
    "exercises": [
      "Zone 2 Running - Outdoor",
      "4x4 Interval Running - Outdoor",
      "Zone 2 Running - Indoor Treadmill",
      "4x4 Interval Running - Indoor Treadmill",
      "Zone 2 Cycling - Outdoor",
      "4x4 Interval Cycling - Outdoor",
      "Zone 2 Cycling - Indoor Stationary Bike",
      "4x4 Interval Cycling - Indoor Stationary Bike",
      "Zone 2 Rowing",
      "4x4 Interval Rowing"
    ],
    "equipment": [
      "Running Shoes",
      "Treadmill",
      "Bicycle",
      "Helmet",
      "Stationary Bike",
      "Rowing Machine"
    ],
    "difficulties": [
      "beginner",
      "intermediate"
    ]
  }
};

// ========== NORWEGIAN INDEXES ==========
export const EXERCISE_INDEX_FULL_NO = `**Available Exercises Database:**

**Shoulders** (8 shown):
  - Sideløft Med Manualer
  - Militærpress (Overhead-Press)
  - Sittende Arnold-Press
  - Sittende Skulderpress
  - Kabel Face Pull
  - Kabel Omvendt Fly
  - Kabel Sideløft
  - Bånd Pull-Apart

**Upper Arms** (12 shown):
  - Stående Hammercurl
  - Stående Manualcurl
  - Stående Stangcurl
  - EZ-Stangcurl
  - Sittende Manualcurl
  - Enarms Liggende Skrå Manualcurl
  - Bryststøttet Skrå Manualcurl
  - Tau Triceps-Ekstensjon
  - French Press
  - Benkdips
  - Enarms Kabel-Triceps-Ekstensjon
  - Stående Over-Hode Tau-Ekstensjon Fra Lav Trinse

**Forearms** (2 shown):
  - Manual Håndleddscurl
  - Manual Håndleddsrotasjon

**Chest** (8 shown):
  - Manualbenkpress
  - Skrå Manualbenkpress
  - Stangbenkpress
  - Stående Kabelflyes
  - Maskinbenkpress (Hammer Strength)
  - Skrå Manualflyes
  - Stående Kabelflyes Lav-Til-Høy
  - Armheving

**Abdomen** (11 shown):
  - Hengende Benløft
  - Planke
  - Sit-up
  - Sykkel-Crunch (Abdominal Air Bike)
  - Dead Bug
  - Liggende Benløft med Hofteløft
  - Hollow Body-Crunch med Armsveip
  - Planke til Push-up
  - Sideplanke Med Hoftedipp
  - Sideplanke Med Rotasjonsgjennomtrekk
  - Renegade-Roing

**Upper Back** (10 shown):
  - Stangroing Stående Fremoverbøyd
  - Sittende Kabelroing
  - Tripod-Hantelroing
  - Foroverbøyd Roing Med Omvendt Grep
  - Omvendt Roing
  - Høystående Båndroing
  - Sittende Enarms Nedtrekk Fra Gulv
  - Nedtrekk
  - Pullup
  - Tau Strak Arm Nedtrekk

**Lower Back** (2 shown):
  - Superman-løft
  - Svømmerløft I Mageleie

**Glutes** (6 shown):
  - Rygghev
  - Setebro Med Kroppsvekt
  - Stang-Setebro
  - Liggende Hofteabduksjon
  - Modifisert Sideplanke Med Hofteabduksjon
  - Ettbens Hip-Thrust

**Upper Legs** (12 shown):
  - Stang Knebøy Bak
  - Bein­ekstensjon
  - Beinpress
  - Kroppsvekt Utfall
  - Ettbens Knebøy Fra Benk
  - Kroppsvekt Bulgarsk Splittknebøy
  - Kroppsvekt Knebøy
  - Assistert Pistol­Knebøy
  - Konvensjonell Markløft
  - Rumensk Markløft (RDL)
  - Nordisk Hamstringscurl
  - Stivbeinsmarkløft

**Lower Legs** (3 shown):
  - Stående Tåhev Med Kroppsvekt
  - Ettbens Stående Tåhev Med Kroppsvekt
  - Unilateral Eksentrisk Stående Tåhev Med Kroppsvekt

**Warmup** (8 shown):
  - Romaskin
  - Stasjonær Sykkel
  - Tredemølle Gange/Jogg (5 ° stigning)
  - Knebøy med Kroppsvekt
  - Bekkentilt
  - Jogging på Stedet
  - Veggpush-ups
  - Armsirkler

**Cardio** (8 shown):
  - Sone 2 Løping – Utendørs
  - 4×4 Intervalløping – Utendørs
  - Sone 2 Løping – Innendørs Tredemølle
  - 4×4 Intervalløping – Innendørs Tredemølle
  - Sone 2 Sykling – Utendørs
  - 4×4 Intervallsykling – Utendørs
  - Sone 2 Sykling – Innendørs
  - 4×4 Intervallsykling – Innendørs Spinningsykkel


**Usage:**
- Reference specific exercise names when making recommendations
- Use <<EXERCISE_QUERY:bodypart:exercise_name>> to display exercise card
- Example: "Try **External Rotation** <<EXERCISE_QUERY:Shoulders:external rotation>>"
`;

export const EXERCISE_INDEX_COMPACT_NO = `**Exercise Database** (reference for specific recommendations):
• Shoulders: Sideløft Med Manualer, Militærpress (Overhead-Press), Sittende Arnold-Press, Sittende Skulderpress, Kabel Face Pull, Kabel Omvendt Fly, Kabel Sideløft, Bånd Pull-Apart, Kabel Utadrotasjon, Båndbasert Sideløft, Kabel Innadrotasjon, Stående Bånd Face Pull...
• Upper Arms: Stående Hammercurl, Stående Manualcurl, Stående Stangcurl, EZ-Stangcurl, Sittende Manualcurl, Enarms Liggende Skrå Manualcurl, Bryststøttet Skrå Manualcurl, Tau Triceps-Ekstensjon, French Press, Benkdips, Enarms Kabel-Triceps-Ekstensjon, Stående Over-Hode Tau-Ekstensjon Fra Lav Trinse, Manual Triceps-Ekstensjon På Flat Benk...
• Forearms: Manual Håndleddscurl, Manual Håndleddsrotasjon...
• Chest: Manualbenkpress, Skrå Manualbenkpress, Stangbenkpress, Stående Kabelflyes, Maskinbenkpress (Hammer Strength), Skrå Manualflyes, Stående Kabelflyes Lav-Til-Høy, Armheving, Stående Kabelflyes Høy-Til-Lav...
• Abdomen: Hengende Benløft, Planke, Sit-up, Sykkel-Crunch (Abdominal Air Bike), Dead Bug, Liggende Benløft med Hofteløft, Hollow Body-Crunch med Armsveip, Planke til Push-up, Spiderman-planke, Mountain Climbers, Sideplanke Med Hoftedipp, Sideplanke Med Rotasjonsgjennomtrekk, Renegade-Roing...
• Upper Back: Stangroing Stående Fremoverbøyd, Sittende Kabelroing, Tripod-Hantelroing, Foroverbøyd Roing Med Omvendt Grep, Omvendt Roing, Høystående Båndroing, Sittende Enarms Nedtrekk Fra Gulv, Nedtrekk, Pullup, Tau Strak Arm Nedtrekk...
• Lower Back: Superman-løft, Svømmerløft I Mageleie...
• Glutes: Rygghev, Setebro Med Kroppsvekt, Stang-Setebro, Liggende Hofteabduksjon, Modifisert Sideplanke Med Hofteabduksjon, Ettbens Hip-Thrust...
• Upper Legs: Stang Knebøy Bak, Bein­ekstensjon, Beinpress, Kroppsvekt Utfall, Ettbens Knebøy Fra Benk, Kroppsvekt Bulgarsk Splittknebøy, Kroppsvekt Knebøy, Assistert Pistol­Knebøy, Ettbens Box-Squat, Veggsitt (Isometrisk Hold), Burpee, Konvensjonell Markløft, Rumensk Markløft (RDL), Nordisk Hamstringscurl, Stivbeinsmarkløft...
• Lower Legs: Stående Tåhev Med Kroppsvekt, Ettbens Stående Tåhev Med Kroppsvekt, Unilateral Eksentrisk Stående Tåhev Med Kroppsvekt...
• Warmup: Romaskin, Stasjonær Sykkel, Tredemølle Gange/Jogg (5 ° stigning), Knebøy med Kroppsvekt, Bekkentilt, Jogging på Stedet, Veggpush-ups, Armsirkler, Stående Rotasjon av Overkropp, Ellipsemaskin, Hoppetau...
• Cardio: Sone 2 Løping – Utendørs, 4×4 Intervalløping – Utendørs, Sone 2 Løping – Innendørs Tredemølle, 4×4 Intervalløping – Innendørs Tredemølle, Sone 2 Sykling – Utendørs, 4×4 Intervallsykling – Utendørs, Sone 2 Sykling – Innendørs, 4×4 Intervallsykling – Innendørs Spinningsykkel, Sone 2 Roing, 4×4 Intervallroing...
`;

export const EXERCISE_INDEX_RAW_NO = {
  "Shoulders": {
    "total": 19,
    "exercises": [
      "Sideløft Med Manualer",
      "Militærpress (Overhead-Press)",
      "Sittende Arnold-Press",
      "Sittende Skulderpress",
      "Kabel Face Pull",
      "Kabel Omvendt Fly",
      "Kabel Sideløft",
      "Bånd Pull-Apart",
      "Kabel Utadrotasjon",
      "Båndbasert Sideløft",
      "Kabel Innadrotasjon",
      "Stående Bånd Face Pull",
      "Enarms Bånd Utadrotasjon",
      "Frontløft Med Manualer, Nøytralt Grep",
      "Skulderløft I Bue",
      "Modifisert Bånd Sideløft",
      "Bånd Skulderfleksjon Med Bøyde Armer",
      "Bånd Skulderfleksjon Med Strake Armer",
      "Side­liggende Utadrotasjon Med Manual"
    ],
    "equipment": [
      "Dumbbell",
      "Barbell",
      "Cable",
      "Bands",
      "Machine"
    ],
    "difficulties": [
      "beginner",
      "intermediate"
    ]
  },
  "Upper Arms (Biceps)": {
    "total": 7,
    "exercises": [
      "Stående Hammercurl",
      "Stående Manualcurl",
      "Stående Stangcurl",
      "EZ-Stangcurl",
      "Sittende Manualcurl",
      "Enarms Liggende Skrå Manualcurl",
      "Bryststøttet Skrå Manualcurl"
    ],
    "equipment": [
      "Dumbbell",
      "Barbell",
      "Bench"
    ],
    "difficulties": [
      "beginner"
    ]
  },
  "Upper Arms (Triceps)": {
    "total": 6,
    "exercises": [
      "Tau Triceps-Ekstensjon",
      "French Press",
      "Benkdips",
      "Enarms Kabel-Triceps-Ekstensjon",
      "Stående Over-Hode Tau-Ekstensjon Fra Lav Trinse",
      "Manual Triceps-Ekstensjon På Flat Benk"
    ],
    "equipment": [
      "Cable",
      "Barbell",
      "Bodyweight",
      "Dumbbell",
      "Bench"
    ],
    "difficulties": [
      "beginner"
    ]
  },
  "Forearms": {
    "total": 2,
    "exercises": [
      "Manual Håndleddscurl",
      "Manual Håndleddsrotasjon"
    ],
    "equipment": [
      "Dumbbell",
      "Bench"
    ],
    "difficulties": [
      "beginner"
    ]
  },
  "Chest": {
    "total": 9,
    "exercises": [
      "Manualbenkpress",
      "Skrå Manualbenkpress",
      "Stangbenkpress",
      "Stående Kabelflyes",
      "Maskinbenkpress (Hammer Strength)",
      "Skrå Manualflyes",
      "Stående Kabelflyes Lav-Til-Høy",
      "Armheving",
      "Stående Kabelflyes Høy-Til-Lav"
    ],
    "equipment": [
      "Dumbbell",
      "Barbell",
      "Cable",
      "Machine",
      "Bodyweight"
    ],
    "difficulties": [
      "beginner",
      "intermediate"
    ]
  },
  "Abdomen (Abs)": {
    "total": 10,
    "exercises": [
      "Hengende Benløft",
      "Planke",
      "Sit-up",
      "Sykkel-Crunch (Abdominal Air Bike)",
      "Dead Bug",
      "Liggende Benløft med Hofteløft",
      "Hollow Body-Crunch med Armsveip",
      "Planke til Push-up",
      "Spiderman-planke",
      "Mountain Climbers"
    ],
    "equipment": [
      "Bodyweight"
    ],
    "difficulties": [
      "advanced",
      "beginner",
      "intermediate"
    ]
  },
  "Abdomen (Obliques)": {
    "total": 3,
    "exercises": [
      "Sideplanke Med Hoftedipp",
      "Sideplanke Med Rotasjonsgjennomtrekk",
      "Renegade-Roing"
    ],
    "equipment": [
      "Bodyweight",
      "Dumbbell"
    ],
    "difficulties": [
      "beginner",
      "intermediate"
    ]
  },
  "Upper Back": {
    "total": 7,
    "exercises": [
      "Stangroing Stående Fremoverbøyd",
      "Sittende Kabelroing",
      "Tripod-Hantelroing",
      "Foroverbøyd Roing Med Omvendt Grep",
      "Omvendt Roing",
      "Høystående Båndroing",
      "Sittende Enarms Nedtrekk Fra Gulv"
    ],
    "equipment": [
      "Barbell",
      "Cable",
      "Dumbbell",
      "Bodyweight",
      "Smith Machine",
      "TRX",
      "Rings",
      "Bands"
    ],
    "difficulties": [
      "beginner",
      "intermediate"
    ]
  },
  "Upper Back (Lats)": {
    "total": 3,
    "exercises": [
      "Nedtrekk",
      "Pullup",
      "Tau Strak Arm Nedtrekk"
    ],
    "equipment": [
      "Cable",
      "Bodyweight"
    ],
    "difficulties": [
      "beginner"
    ]
  },
  "Lower Back": {
    "total": 2,
    "exercises": [
      "Superman-løft",
      "Svømmerløft I Mageleie"
    ],
    "equipment": [
      "Bodyweight"
    ],
    "difficulties": [
      "beginner"
    ]
  },
  "Glutes": {
    "total": 6,
    "exercises": [
      "Rygghev",
      "Setebro Med Kroppsvekt",
      "Stang-Setebro",
      "Liggende Hofteabduksjon",
      "Modifisert Sideplanke Med Hofteabduksjon",
      "Ettbens Hip-Thrust"
    ],
    "equipment": [
      "Bodyweight",
      "Barbell",
      "Bench"
    ],
    "difficulties": [
      "beginner",
      "intermediate"
    ]
  },
  "Upper Legs (Quads)": {
    "total": 11,
    "exercises": [
      "Stang Knebøy Bak",
      "Bein­ekstensjon",
      "Beinpress",
      "Kroppsvekt Utfall",
      "Ettbens Knebøy Fra Benk",
      "Kroppsvekt Bulgarsk Splittknebøy",
      "Kroppsvekt Knebøy",
      "Assistert Pistol­Knebøy",
      "Ettbens Box-Squat",
      "Veggsitt (Isometrisk Hold)",
      "Burpee"
    ],
    "equipment": [
      "Barbell",
      "Machine",
      "Bodyweight",
      "Bench",
      "TRX",
      "Bands"
    ],
    "difficulties": [
      "intermediate",
      "beginner"
    ]
  },
  "Upper Legs (Hamstrings)": {
    "total": 5,
    "exercises": [
      "Konvensjonell Markløft",
      "Rumensk Markløft (RDL)",
      "Nordisk Hamstringscurl",
      "Stivbeinsmarkløft",
      "Ettbens Rumensk Markløft"
    ],
    "equipment": [
      "Barbell",
      "Bodyweight",
      "Kettlebell",
      "Dumbbell",
      "Weight Plate"
    ],
    "difficulties": [
      "intermediate",
      "beginner",
      "advanced"
    ]
  },
  "Lower Legs (Calves)": {
    "total": 3,
    "exercises": [
      "Stående Tåhev Med Kroppsvekt",
      "Ettbens Stående Tåhev Med Kroppsvekt",
      "Unilateral Eksentrisk Stående Tåhev Med Kroppsvekt"
    ],
    "equipment": [
      "Bodyweight"
    ],
    "difficulties": [
      "beginner",
      "intermediate"
    ]
  },
  "Warmup": {
    "total": 11,
    "exercises": [
      "Romaskin",
      "Stasjonær Sykkel",
      "Tredemølle Gange/Jogg (5 ° stigning)",
      "Knebøy med Kroppsvekt",
      "Bekkentilt",
      "Jogging på Stedet",
      "Veggpush-ups",
      "Armsirkler",
      "Stående Rotasjon av Overkropp",
      "Ellipsemaskin",
      "Hoppetau"
    ],
    "equipment": [
      "Rowing Machine",
      "Stationary Bike",
      "Treadmill",
      "Bodyweight",
      "Elliptical Machine",
      "Jump Rope"
    ],
    "difficulties": [
      "beginner"
    ]
  },
  "Cardio": {
    "total": 10,
    "exercises": [
      "Sone 2 Løping – Utendørs",
      "4×4 Intervalløping – Utendørs",
      "Sone 2 Løping – Innendørs Tredemølle",
      "4×4 Intervalløping – Innendørs Tredemølle",
      "Sone 2 Sykling – Utendørs",
      "4×4 Intervallsykling – Utendørs",
      "Sone 2 Sykling – Innendørs",
      "4×4 Intervallsykling – Innendørs Spinningsykkel",
      "Sone 2 Roing",
      "4×4 Intervallroing"
    ],
    "equipment": [
      "Running Shoes",
      "Treadmill",
      "Bicycle",
      "Helmet",
      "Stationary Bike",
      "Rowing Machine"
    ],
    "difficulties": [
      "beginner",
      "intermediate"
    ]
  }
};

// ========== LEGACY EXPORTS (for backwards compatibility) ==========
export const EXERCISE_INDEX_FULL = EXERCISE_INDEX_FULL_EN;
export const EXERCISE_INDEX_COMPACT = EXERCISE_INDEX_COMPACT_EN;
export const EXERCISE_INDEX_RAW = EXERCISE_INDEX_RAW_EN;
