// AUTO-GENERATED by scripts/generate-exercise-index.ts
// Do not edit manually - regenerate using: npm run generate-exercise-index

export const EXERCISE_INDEX_FULL = `**Available Exercises Database:**

**Shoulders** (8 shown):
  - Dumbbell Lateral Raise
  - Military Press (AKA Overhead Press)
  - Seated Arnold Press
  - Seated Shoulder Press
  - Cable Face Pull
  - Cable Reverse Fly
  - Cable Lateral Raise
  - Band Pull Apart

**Upper Arms** (12 shown):
  - Standing Hammer Curl
  - Standing Dumbbell Curl
  - Standing Barbell Curl
  - EZ Bar Curl
  - Seated Dumbbell Curl
  - One-Arm Prone Incline Dumbbell Curl
  - Chest-Supported Incline Dumbbell Curl
  - Rope Tricep Extension
  - French Press
  - Bench Dip
  - One-Arm Cable Tricep Extension
  - Standing Low Pulley Overhead Tricep Extension (Rope Extension)

**Forearms** (2 shown):
  - Dumbbell Wrist Curl
  - Dumbbell Wrist Rotation

**Chest** (8 shown):
  - Dumbbell Bench Press
  - Incline Dumbbell Bench Press
  - Barbell Bench Press
  - Standing Cable Fly
  - Hammer Strength Bench Press
  - Incline Dumbbell Flys
  - Standing Low to High Cable Fly
  - Push Up

**Abdomen** (11 shown):
  - Hanging Leg Raise
  - Plank
  - Sit Up
  - Abdominal Air Bike (AKA Bicycle)
  - Dead Bug
  - Lying Leg Raise With Hip Thrust
  - Hollow Body Crunch with Arm Sweep
  - Plank to Push-Up
  - Side Plank with Hip Dip
  - Side Plank with Rotational Reach-Through
  - Renegade Row

**Upper Back** (10 shown):
  - Bent Over Row
  - Seated Cable Row
  - Tripod Dumbbell Row
  - Reverse Grip Bent Over Row
  - Inverted Row
  - High Standing Banded Row
  - Seated Floor Single-Arm Cable Lat Pulldown
  - Lat Pull Down
  - Pull Up
  - Rope Straight Arm Pull Down

**Lower Back** (2 shown):
  - Superman Raise
  - Prone Swimmer Raises

**Glutes** (6 shown):
  - Hyperextension
  - Bodyweight Glute Bridge
  - Barbell Glute Bridge
  - Side Lying Hip Abduction
  - Modified Side Plank Hip Abduction
  - Single-Leg Hip Thrust

**Upper Legs** (12 shown):
  - Barbell Back Squat
  - Leg Extension
  - Leg Press
  - Bodyweight Lunge
  - Single Leg Squat From Bench
  - Bodyweight Bulgarian Split Squat
  - Bodyweight Squat
  - Assisted Pistol Squat
  - Conventional Deadlift
  - Romanian Deadlift (AKA RDL)
  - Nordic Hamstring Curl
  - Straight Leg Deadlift

**Lower Legs** (3 shown):
  - Bodyweight Standing Calf Raise
  - One-Leg Standing Bodyweight Calf Raise
  - Unilateral Eccentric Bodyweight Standing Calf Raise

**Warmup** (8 shown):
  - Rowing Machine
  - Stationary Bike
  - Treadmill Walk/Jog (5° Incline)
  - Bodyweight Squat
  - Pelvic Tilt
  - Jogging in Place
  - Wall Push-Ups
  - Arm Circles

**Cardio** (8 shown):
  - Zone 2 Running - Outdoor
  - 4x4 Interval Running - Outdoor
  - Zone 2 Running - Indoor Treadmill
  - 4x4 Interval Running - Indoor Treadmill
  - Zone 2 Cycling - Outdoor
  - 4x4 Interval Cycling - Outdoor
  - Zone 2 Cycling - Indoor Stationary Bike
  - 4x4 Interval Cycling - Indoor Stationary Bike


**Usage:**
- Reference specific exercise names when making recommendations
- Use <<EXERCISE_QUERY:bodypart:exercise_name>> to display exercise card
- Example: "Try **External Rotation** <<EXERCISE_QUERY:Shoulders:external rotation>>"
`;

export const EXERCISE_INDEX_COMPACT = `**Exercise Database** (reference for specific recommendations):
• Shoulders: Dumbbell Lateral Raise, Military Press (AKA Overhead Press), Seated Arnold Press, Seated Shoulder Press, Cable Face Pull, Cable Reverse Fly, Cable Lateral Raise, Band Pull Apart, Cable External Rotation, Banded Lateral Raise, Cable Internal Rotation, Standing Banded Face Pull...
• Upper Arms: Standing Hammer Curl, Standing Dumbbell Curl, Standing Barbell Curl, EZ Bar Curl, Seated Dumbbell Curl, One-Arm Prone Incline Dumbbell Curl, Chest-Supported Incline Dumbbell Curl, Rope Tricep Extension, French Press, Bench Dip, One-Arm Cable Tricep Extension, Standing Low Pulley Overhead Tricep Extension (Rope Extension), Dumbbell Tricep Extension...
• Forearms: Dumbbell Wrist Curl, Dumbbell Wrist Rotation...
• Chest: Dumbbell Bench Press, Incline Dumbbell Bench Press, Barbell Bench Press, Standing Cable Fly, Hammer Strength Bench Press, Incline Dumbbell Flys, Standing Low to High Cable Fly, Push Up, Standing High to Low Cable Fly...
• Abdomen: Hanging Leg Raise, Plank, Sit Up, Abdominal Air Bike (AKA Bicycle), Dead Bug, Lying Leg Raise With Hip Thrust, Hollow Body Crunch with Arm Sweep, Plank to Push-Up, Spiderman Plank, Mountain Climbers, Side Plank with Hip Dip, Side Plank with Rotational Reach-Through, Renegade Row...
• Upper Back: Bent Over Row, Seated Cable Row, Tripod Dumbbell Row, Reverse Grip Bent Over Row, Inverted Row, High Standing Banded Row, Seated Floor Single-Arm Cable Lat Pulldown, Lat Pull Down, Pull Up, Rope Straight Arm Pull Down...
• Lower Back: Superman Raise, Prone Swimmer Raises...
• Glutes: Hyperextension, Bodyweight Glute Bridge, Barbell Glute Bridge, Side Lying Hip Abduction, Modified Side Plank Hip Abduction, Single-Leg Hip Thrust...
• Upper Legs: Barbell Back Squat, Leg Extension, Leg Press, Bodyweight Lunge, Single Leg Squat From Bench, Bodyweight Bulgarian Split Squat, Bodyweight Squat, Assisted Pistol Squat, Single-Leg Box Squat (Sit-to-Stand), Wall Sit (Isometric Hold), Burpee, Conventional Deadlift, Romanian Deadlift (AKA RDL), Nordic Hamstring Curl, Straight Leg Deadlift...
• Lower Legs: Bodyweight Standing Calf Raise, One-Leg Standing Bodyweight Calf Raise, Unilateral Eccentric Bodyweight Standing Calf Raise...
• Warmup: Rowing Machine, Stationary Bike, Treadmill Walk/Jog (5° Incline), Bodyweight Squat, Pelvic Tilt, Jogging in Place, Wall Push-Ups, Arm Circles, Standing Trunk Rotation, Elliptical Machine, Jump Rope...
• Cardio: Zone 2 Running - Outdoor, 4x4 Interval Running - Outdoor, Zone 2 Running - Indoor Treadmill, 4x4 Interval Running - Indoor Treadmill, Zone 2 Cycling - Outdoor, 4x4 Interval Cycling - Outdoor, Zone 2 Cycling - Indoor Stationary Bike, 4x4 Interval Cycling - Indoor Stationary Bike, Zone 2 Rowing, 4x4 Interval Rowing...
`;

export const EXERCISE_INDEX_RAW = {
  "Shoulders": {
    "total": 19,
    "exercises": [
      "Dumbbell Lateral Raise",
      "Military Press (AKA Overhead Press)",
      "Seated Arnold Press",
      "Seated Shoulder Press",
      "Cable Face Pull",
      "Cable Reverse Fly",
      "Cable Lateral Raise",
      "Band Pull Apart",
      "Cable External Rotation",
      "Banded Lateral Raise",
      "Cable Internal Rotation",
      "Standing Banded Face Pull",
      "Single Arm Banded External Rotation",
      "Neutral Grip Dumbbell Front Raise",
      "Arc Shoulder Raise",
      "Modified Banded Lateral Raise",
      "Banded Shoulder Flexion Raise",
      "Straight-Arm Banded Shoulder Flexion Raise",
      "Side-Lying Shoulder External Rotation"
    ],
    "equipment": [
      "Dumbbell",
      "Barbell",
      "Cable",
      "Bands",
      "Machine"
    ],
    "difficulties": [
      "beginner",
      "intermediate"
    ]
  },
  "Upper Arms (Biceps)": {
    "total": 7,
    "exercises": [
      "Standing Hammer Curl",
      "Standing Dumbbell Curl",
      "Standing Barbell Curl",
      "EZ Bar Curl",
      "Seated Dumbbell Curl",
      "One-Arm Prone Incline Dumbbell Curl",
      "Chest-Supported Incline Dumbbell Curl"
    ],
    "equipment": [
      "Dumbbell",
      "Barbell",
      "Bench"
    ],
    "difficulties": [
      "beginner"
    ]
  },
  "Upper Arms (Triceps)": {
    "total": 6,
    "exercises": [
      "Rope Tricep Extension",
      "French Press",
      "Bench Dip",
      "One-Arm Cable Tricep Extension",
      "Standing Low Pulley Overhead Tricep Extension (Rope Extension)",
      "Dumbbell Tricep Extension"
    ],
    "equipment": [
      "Cable",
      "Barbell",
      "Bodyweight",
      "Dumbbell",
      "Bench"
    ],
    "difficulties": [
      "beginner"
    ]
  },
  "Forearms": {
    "total": 2,
    "exercises": [
      "Dumbbell Wrist Curl",
      "Dumbbell Wrist Rotation"
    ],
    "equipment": [
      "Dumbbell",
      "Bench"
    ],
    "difficulties": [
      "beginner"
    ]
  },
  "Chest": {
    "total": 9,
    "exercises": [
      "Dumbbell Bench Press",
      "Incline Dumbbell Bench Press",
      "Barbell Bench Press",
      "Standing Cable Fly",
      "Hammer Strength Bench Press",
      "Incline Dumbbell Flys",
      "Standing Low to High Cable Fly",
      "Push Up",
      "Standing High to Low Cable Fly"
    ],
    "equipment": [
      "Dumbbell",
      "Barbell",
      "Cable",
      "Machine",
      "Bodyweight"
    ],
    "difficulties": [
      "beginner",
      "intermediate"
    ]
  },
  "Abdomen (Abs)": {
    "total": 10,
    "exercises": [
      "Hanging Leg Raise",
      "Plank",
      "Sit Up",
      "Abdominal Air Bike (AKA Bicycle)",
      "Dead Bug",
      "Lying Leg Raise With Hip Thrust",
      "Hollow Body Crunch with Arm Sweep",
      "Plank to Push-Up",
      "Spiderman Plank",
      "Mountain Climbers"
    ],
    "equipment": [
      "Bodyweight"
    ],
    "difficulties": [
      "advanced",
      "beginner",
      "intermediate"
    ]
  },
  "Abdomen (Obliques)": {
    "total": 3,
    "exercises": [
      "Side Plank with Hip Dip",
      "Side Plank with Rotational Reach-Through",
      "Renegade Row"
    ],
    "equipment": [
      "Bodyweight",
      "Dumbbell"
    ],
    "difficulties": [
      "beginner",
      "intermediate"
    ]
  },
  "Upper Back": {
    "total": 7,
    "exercises": [
      "Bent Over Row",
      "Seated Cable Row",
      "Tripod Dumbbell Row",
      "Reverse Grip Bent Over Row",
      "Inverted Row",
      "High Standing Banded Row",
      "Seated Floor Single-Arm Cable Lat Pulldown"
    ],
    "equipment": [
      "Barbell",
      "Cable",
      "Dumbbell",
      "Bodyweight",
      "Smith Machine",
      "TRX",
      "Rings",
      "Bands"
    ],
    "difficulties": [
      "beginner",
      "intermediate"
    ]
  },
  "Upper Back (Lats)": {
    "total": 3,
    "exercises": [
      "Lat Pull Down",
      "Pull Up",
      "Rope Straight Arm Pull Down"
    ],
    "equipment": [
      "Cable",
      "Bodyweight"
    ],
    "difficulties": [
      "beginner"
    ]
  },
  "Lower Back": {
    "total": 2,
    "exercises": [
      "Superman Raise",
      "Prone Swimmer Raises"
    ],
    "equipment": [
      "Bodyweight"
    ],
    "difficulties": [
      "beginner"
    ]
  },
  "Glutes": {
    "total": 6,
    "exercises": [
      "Hyperextension",
      "Bodyweight Glute Bridge",
      "Barbell Glute Bridge",
      "Side Lying Hip Abduction",
      "Modified Side Plank Hip Abduction",
      "Single-Leg Hip Thrust"
    ],
    "equipment": [
      "Bodyweight",
      "Barbell",
      "Bench"
    ],
    "difficulties": [
      "beginner",
      "intermediate"
    ]
  },
  "Upper Legs (Quads)": {
    "total": 11,
    "exercises": [
      "Barbell Back Squat",
      "Leg Extension",
      "Leg Press",
      "Bodyweight Lunge",
      "Single Leg Squat From Bench",
      "Bodyweight Bulgarian Split Squat",
      "Bodyweight Squat",
      "Assisted Pistol Squat",
      "Single-Leg Box Squat (Sit-to-Stand)",
      "Wall Sit (Isometric Hold)",
      "Burpee"
    ],
    "equipment": [
      "Barbell",
      "Machine",
      "Bodyweight",
      "Bench",
      "TRX",
      "Bands"
    ],
    "difficulties": [
      "intermediate",
      "beginner"
    ]
  },
  "Upper Legs (Hamstrings)": {
    "total": 5,
    "exercises": [
      "Conventional Deadlift",
      "Romanian Deadlift (AKA RDL)",
      "Nordic Hamstring Curl",
      "Straight Leg Deadlift",
      "Single-Leg Romanian Deadlift"
    ],
    "equipment": [
      "Barbell",
      "Bodyweight",
      "Kettlebell",
      "Dumbbell",
      "Weight Plate"
    ],
    "difficulties": [
      "intermediate",
      "beginner",
      "advanced"
    ]
  },
  "Lower Legs (Calves)": {
    "total": 3,
    "exercises": [
      "Bodyweight Standing Calf Raise",
      "One-Leg Standing Bodyweight Calf Raise",
      "Unilateral Eccentric Bodyweight Standing Calf Raise"
    ],
    "equipment": [
      "Bodyweight"
    ],
    "difficulties": [
      "beginner",
      "intermediate"
    ]
  },
  "Warmup": {
    "total": 11,
    "exercises": [
      "Rowing Machine",
      "Stationary Bike",
      "Treadmill Walk/Jog (5° Incline)",
      "Bodyweight Squat",
      "Pelvic Tilt",
      "Jogging in Place",
      "Wall Push-Ups",
      "Arm Circles",
      "Standing Trunk Rotation",
      "Elliptical Machine",
      "Jump Rope"
    ],
    "equipment": [
      "Rowing Machine",
      "Stationary Bike",
      "Treadmill",
      "Bodyweight",
      "Elliptical Machine",
      "Jump Rope"
    ],
    "difficulties": [
      "beginner"
    ]
  },
  "Cardio": {
    "total": 10,
    "exercises": [
      "Zone 2 Running - Outdoor",
      "4x4 Interval Running - Outdoor",
      "Zone 2 Running - Indoor Treadmill",
      "4x4 Interval Running - Indoor Treadmill",
      "Zone 2 Cycling - Outdoor",
      "4x4 Interval Cycling - Outdoor",
      "Zone 2 Cycling - Indoor Stationary Bike",
      "4x4 Interval Cycling - Indoor Stationary Bike",
      "Zone 2 Rowing",
      "4x4 Interval Rowing"
    ],
    "equipment": [
      "Running Shoes",
      "Treadmill",
      "Bicycle",
      "Helmet",
      "Stationary Bike",
      "Rowing Machine"
    ],
    "difficulties": [
      "beginner",
      "intermediate"
    ]
  }
};
