export interface BodyPartGroup {
  name: string;
  ids: string[];
  keywords: string[];
}

export const bodyPartGroups: { [key: string]: BodyPartGroup } = {
  neck: {
    name: 'Neck',
    ids: [
      'muscular_system-sternocleidomastoid_ID',
      'muscular_system-right_sternocleidomastoid_ID',
      'muscular_system-left_sternocleidomastoid_ID',
      'muscular_system-platysma_ID',
      'muscular_system-right_platysma_ID',
      'muscular_system-left_platysma_ID',
      'muscular_system-anterior_scalene_ID',
      'muscular_system-right_anterior_scalene_ID',
      'muscular_system-left_anterior_scalene_ID',
      'muscular_system-middle_scalene_ID',
      'muscular_system-right_middle_scalene_ID',
      'muscular_system-left_middle_scalene_ID',
      'muscular_system-posterior_scalene_ID',
      'muscular_system-right_posterior_scalene_ID',
      'muscular_system-left_posterior_scalene_ID',
      'muscular_system-sternohyoid_ID',
      'muscular_system-right_sternohyoid_ID',
      'muscular_system-left_sternohyoid_ID',
      'muscular_system-omohyoid_ID',
      'muscular_system-right_superior_belly_of_omohyoid_ID',
      'muscular_system-left_superior_belly_of_omohyoid_ID',
      'muscular_system-right_inferior_belly_of_omohyoid_ID',
      'muscular_system-left_inferior_belly_of_omohyoid_ID',
      'muscular_system-thyrohyoid_ID',
      'muscular_system-right_thyrohyoid_ID',
      'muscular_system-left_thyrohyoid_ID',
      'muscular_system-sternothyroid_ID',
      'muscular_system-right_sternothyroid_ID',
      'muscular_system-left_sternothyroid_ID',
      'muscular_system-rectus_capitis_posterior_minor_ID',
      'muscular_system-right_rectus_capitis_posterior_minor_ID',
      'muscular_system-left_rectus_capitis_posterior_minor_ID',
      'muscular_system-rectus_capitis_posterior_major_ID',
      'muscular_system-right_rectus_capitis_posterior_major_ID',
      'muscular_system-left_rectus_capitis_posterior_major_ID',
      'muscular_system-obliquus_capitis_superior_ID',
      'muscular_system-right_obliquus_capitis_superior_ID',
      'muscular_system-left_obliquus_capitis_superior_ID',
      'muscular_system-obliquus_capitis_inferior_ID',
      'muscular_system-right_obliquus_capitis_inferior_ID',
      'muscular_system-left_obliquus_capitis_inferior_ID',
      'connective_tissue-anterior_longitudinal_ligament_ID',
      'connective_tissue-ligamentum_nuchae_ID',
      'muscular_system-left_splenius_capitis_ID',
      'muscular_system-right_splenius_capitis_ID',
    ],
    keywords: ['neck', 'cervical', 'throat', 'laryn', 'pharyn'],
  },
  leftShoulder: {
    name: 'Left Shoulder',
    ids: [
      'muscular_system-left_deltoid_ID',
      'muscular_system-left_teres_major_ID',
      'muscular_system-left_supraspinatus_ID',
      'muscular_system-left_infraspinatus_ID',
      'muscular_system-left_teres_minor_ID',
      'muscular_system-left_subscapularis_ID',
      'connective_tissue-left_acromioclavicular_ligament_ID',
      'connective_tissue-left_coracoacromial_ligament_ID',
      'connective_tissue-left_coracoclavicular_ligament_ID',
      'connective_tissue-left_glenohumeral_ligaments_ID',
    ],
    keywords: ['left shoulder', 'left deltoid'],
  },
  rightShoulder: {
    name: 'Right Shoulder',
    ids: [
      'muscular_system-right_deltoid_ID',
      'muscular_system-right_teres_major_ID',
      'muscular_system-right_supraspinatus_ID',
      'muscular_system-right_infraspinatus_ID',
      'muscular_system-right_teres_minor_ID',
      'muscular_system-right_subscapularis_ID',
      'connective_tissue-right_acromioclavicular_ligament_ID',
      'connective_tissue-right_coracoacromial_ligament_ID',
      'connective_tissue-right_coracoclavicular_ligament_ID',
      'connective_tissue-right_glenohumeral_ligaments_ID',
    ],
    keywords: ['right shoulder', 'right deltoid'],
  },
  leftUpperArm: {
    name: 'Left Upper Arm',
    ids: [
      'muscular_system-left_biceps_brachii_ID',
      'muscular_system-left_brachialis_ID',
      'muscular_system-left_triceps_brachii_ID',
      'muscular_system-left_coracobrachialis_ID',
      'connective_tissue-left_bicipital_aponeurosis_ID',
    ],
    keywords: ['left biceps', 'left triceps', 'left brachii'],
  },
  rightUpperArm: {
    name: 'Right Upper Arm',
    ids: [
      'muscular_system-right_biceps_brachii_ID',
      'muscular_system-right_brachialis_ID',
      'muscular_system-right_triceps_brachii_ID',
      'muscular_system-right_coracobrachialis_ID',
      'connective_tissue-right_bicipital_aponeurosis_ID',
    ],
    keywords: ['right biceps', 'right triceps', 'right brachii'],
  },
  leftElbow: {
    name: 'Left Elbow',
    ids: [
      'muscular_system-left_anconeus_ID',
      'connective_tissue-left_annular_ligament_ID',
      'connective_tissue-left_ulnar_collateral_ligament_ID',
      'connective_tissue-left_joint_capsule_ID',
      'connective_tissue-left_subcutaneous_olecranon_bursa_ID',
      'connective_tissue-left_elbow_joint_capsule_ID',
      'skeletal_system-left_humerus_ID',
      'skeletal_system-left_radius_ID',
      'connective_tissue-left_posterior_part_of_ulnar_collateral_ligament_ID',
      'muscular_system-left_bicipital_aponeurosis_ID',
      'connective_tissue-left_bicipitoradial_bursa_ID',
    ],
    keywords: ['left elbow'],
  },
  rightElbow: {
    name: 'Right Elbow',
    ids: [
      'muscular_system-right_anconeus_ID',
      'connective_tissue-right_annular_ligament_ID',
      'connective_tissue-right_ulnar_collateral_ligament_ID',
      'connective_tissue-right_joint_capsule_ID',
      'connective_tissue-right_subcutaneous_olecranon_bursa_ID',
      'connective_tissue-right_elbow_joint_capsule_ID',
      'skeletal_system-right_humerus_ID',
      'skeletal_system-right_radius_ID',
      'connective_tissue-right_posterior_part_of_ulnar_collateral_ligament_ID',
      'muscular_system-right_bicipital_aponeurosis_ID',
      'connective_tissue-right_bicipitoradial_bursa_ID',
    ],
    keywords: ['right elbow'],
  },
  leftForearmHand: {
    name: 'Left Forearm and Hand',
    ids: [
      'muscular_system-left_palmaris_longus_ID',
      'muscular_system-left_flexor_carpi_radialis_ID',
      'muscular_system-left_flexor_carpi_ulnaris_ID',
      'muscular_system-left_flexor_digitorum_superficialis_ID',
      'muscular_system-left_flexor_digitorum_profundus_ID',
      'muscular_system-left_flexor_pollicis_longus_ID',
      'muscular_system-left_pronator_teres_ID',
      'muscular_system-left_pronator_quadratus_ID',
      'muscular_system-left_extensor_carpi_radialis_longus_ID',
      'muscular_system-left_extensor_carpi_radialis_brevis_ID',
      'muscular_system-left_extensor_carpi_ulnaris_ID',
      'muscular_system-left_extensor_digitorum_ID',
      'muscular_system-left_extensor_digiti_minimi_ID',
      'muscular_system-left_extensor_indicis_ID',
      'muscular_system-left_extensor_pollicis_longus_ID',
      'muscular_system-left_extensor_pollicis_brevis_ID',
      'muscular_system-left_abductor_pollicis_longus_ID',
      'muscular_system-left_brachioradialis_ID',
      'muscular_system-left_abductor_pollicis_brevis_ID',
      'muscular_system-left_flexor_pollicis_brevis_ID',
      'muscular_system-left_adductor_pollicis_ID',
      'muscular_system-left_opponens_pollicis_ID',
      'muscular_system-left_flexor_digiti_minimi_brevis_of_hand_ID',
      'muscular_system-left_opponens_digiti_minimi_ID',
      'muscular_system-left_palmaris_brevis_ID',
      'muscular_system-first_lumbrical_muscle_of_left_hand_ID',
      'muscular_system-second_lumbrical_muscle_of_left_hand_ID',
      'muscular_system-third_lumbrical_muscle_of_left_hand_ID',
      'muscular_system-fourth_lumbrical_muscle_of_left_hand_ID',
      'muscular_system-first_palmar_interosseous_muscle_of_left_hand_ID',
      'muscular_system-second_palmar_interosseous_muscle_of_left_hand_ID',
      'muscular_system-third_palmar_interosseous_muscle_of_left_hand_ID',
      'muscular_system-first_dorsal_interosseous_muscle_of_left_hand_ID',
      'muscular_system-second_dorsal_interosseous_muscle_of_left_hand_ID',
      'muscular_system-third_dorsal_interosseous_muscle_of_left_hand_ID',
      'muscular_system-fourth_dorsal_interosseous_muscle_of_left_hand_ID',
      'connective_tissue-left_palmar_aponeurosis_ID',
      'connective_tissue-left_extensor_retinaculum_ID',
      'connective_tissue-left_flexor_retinaculum_ID',
      'skeletal_system-left_ulna_ID',
    ],
    keywords: ['left forearm', 'left hand', 'left wrist'],
  },
  rightForearmHand: {
    name: 'Right Forearm and Hand',
    ids: [
      'muscular_system-right_palmaris_longus_ID',
      'muscular_system-right_flexor_carpi_radialis_ID',
      'muscular_system-right_flexor_carpi_ulnaris_ID',
      'muscular_system-right_flexor_digitorum_superficialis_ID',
      'muscular_system-right_flexor_digitorum_profundus_ID',
      'muscular_system-right_flexor_pollicis_longus_ID',
      'muscular_system-right_pronator_teres_ID',
      'muscular_system-right_pronator_quadratus_ID',
      'muscular_system-right_extensor_carpi_radialis_longus_ID',
      'muscular_system-right_extensor_carpi_radialis_brevis_ID',
      'muscular_system-right_extensor_carpi_ulnaris_ID',
      'muscular_system-right_extensor_digitorum_ID',
      'muscular_system-right_extensor_digiti_minimi_ID',
      'muscular_system-right_extensor_indicis_ID',
      'muscular_system-right_extensor_pollicis_longus_ID',
      'muscular_system-right_extensor_pollicis_brevis_ID',
      'muscular_system-right_abductor_pollicis_longus_ID',
      'muscular_system-right_brachioradialis_ID',
      'muscular_system-right_abductor_pollicis_brevis_ID',
      'muscular_system-right_flexor_pollicis_brevis_ID',
      'muscular_system-right_adductor_pollicis_ID',
      'muscular_system-right_opponens_pollicis_ID',
      'muscular_system-right_flexor_digiti_minimi_brevis_of_hand_ID',
      'muscular_system-right_opponens_digiti_minimi_ID',
      'muscular_system-right_palmaris_brevis_ID',
      'muscular_system-first_lumbrical_muscle_of_right_hand_ID',
      'muscular_system-second_lumbrical_muscle_of_right_hand_ID',
      'muscular_system-third_lumbrical_muscle_of_right_hand_ID',
      'muscular_system-fourth_lumbrical_muscle_of_right_hand_ID',
      'muscular_system-first_palmar_interosseous_muscle_of_right_hand_ID',
      'muscular_system-second_palmar_interosseous_muscle_of_right_hand_ID',
      'muscular_system-third_palmar_interosseous_muscle_of_right_hand_ID',
      'muscular_system-first_dorsal_interosseous_muscle_of_right_hand_ID',
      'muscular_system-second_dorsal_interosseous_muscle_of_right_hand_ID',
      'muscular_system-third_dorsal_interosseous_muscle_of_right_hand_ID',
      'muscular_system-fourth_dorsal_interosseous_muscle_of_right_hand_ID',
      'connective_tissue-right_palmar_aponeurosis_ID',
      'connective_tissue-right_extensor_retinaculum_ID',
      'connective_tissue-right_flexor_retinaculum_ID',
      'skeletal_system-right_ulna_ID',
    ],
    keywords: ['right forearm', 'right hand', 'right wrist'],
  },
  chest: {
    name: 'Chest',
    ids: [
      'muscular_system-pectoralis_major_ID',
      'muscular_system-right_pectoralis_major_ID',
      'muscular_system-left_pectoralis_major_ID',
      'muscular_system-pectoralis_minor_ID',
      'muscular_system-right_pectoralis_minor_ID',
      'muscular_system-left_pectoralis_minor_ID',
      'muscular_system-subclavius_ID',
      'muscular_system-right_subclavius_ID',
      'muscular_system-left_subclavius_ID',
      'muscular_system-serratus_anterior_ID',
      'muscular_system-right_serratus_anterior_ID',
      'muscular_system-left_serratus_anterior_ID',
      'connective_tissue-costal_cartilages_ID',
      'connective_tissue-sternum_ID',
    ],
    keywords: ['pectoral', 'chest'],
  },
  torso: {
    name: 'Torso',
    ids: [
      'muscular_system-rectus_abdominis_ID',
      'muscular_system-right_rectus_abdominis_ID',
      'muscular_system-left_rectus_abdominis_ID',
      'muscular_system-external_oblique_ID',
      'muscular_system-right_external_oblique_ID',
      'muscular_system-left_external_oblique_ID',
      'muscular_system-internal_oblique_ID',
      'muscular_system-right_internal_oblique_ID',
      'muscular_system-left_internal_oblique_ID',
      'muscular_system-transverse_abdominis_ID',
      'muscular_system-right_transverse_abdominis_ID',
      'muscular_system-left_transverse_abdominis_ID',
      'connective_tissue-sternum_ID',
      'connective_tissue-costal_cartilages_ID',
      'connective_tissue-ribs_ID',
      'connective_tissue-right_ribs_ID',
      'connective_tissue-left_ribs_ID',
      'connective_tissue-thoracolumbar_fascia_ID',
    ],
    keywords: ['abdominal', 'sternum', 'rib', 'costal'],
  },
  upperBack: {
    name: 'Upper Back',
    ids: [
      'muscular_system-trapezius_ID',
      'muscular_system-right_trapezius_ID',
      'muscular_system-left_trapezius_ID',
      'muscular_system-rhomboid_major_ID',
      'muscular_system-right_rhomboid_major_ID',
      'muscular_system-left_rhomboid_major_ID',
      'muscular_system-rhomboid_minor_ID',
      'muscular_system-right_rhomboid_minor_ID',
      'muscular_system-left_rhomboid_minor_ID',
      'muscular_system-levator_scapulae_ID',
      'muscular_system-right_levator_scapulae_ID',
      'muscular_system-left_levator_scapulae_ID',
      'connective_tissue-ligamentum_nuchae_ID',
      'connective_tissue-thoracolumbar_fascia_upper_ID',
    ],
    keywords: ['upper back', 'trapezius', 'rhomboid'],
  },
  lowerBack: {
    name: 'Lower Back',
    ids: [
      'muscular_system-left_longissimus_thoracis_ID',
      'muscular_system-right_longissimus_thoracis_ID',
      'muscular_system-right_serratus_posterior_inferior_ID',
      'muscular_system-left_serratus_posterior_inferior_ID',
      'muscular_system-right_longissimus_thoracis_ID',
      'muscular_system-erector_spinae_ID',
      'muscular_system-right_erector_spinae_ID',
      'muscular_system-left_erector_spinae_ID',
      'muscular_system-quadratus_lumborum_ID',
      'muscular_system-right_quadratus_lumborum_ID',
      'muscular_system-left_quadratus_lumborum_ID',
      'muscular_system-multifidus_ID',
      'muscular_system-right_multifidus_ID',
      'muscular_system-left_multifidus_ID',
      'connective_tissue-thoracolumbar_fascia_lower_ID',
      'connective_tissue-anterior_longitudinal_ligament_lumbar_ID',
      'connective_tissue-posterior_longitudinal_ligament_lumbar_ID',
      'connective_tissue-ligamentum_flavum_lumbar_ID',
      'muscular_system-left_latissimus_dorsi_ID',
      'muscular_system-right_latissimus_dorsi_ID',
    ],
    keywords: ['lower back', 'lumbar'],
  },
  pelvisHip: {
    name: 'Pelvis & Hip Region',
    ids: [
      'muscular_system-iliopsoas_ID',
      'muscular_system-right_iliopsoas_ID',
      'muscular_system-left_iliopsoas_ID',
      'muscular_system-psoas_major_ID',
      'muscular_system-right_psoas_major_ID',
      'muscular_system-left_psoas_major_ID',
      'muscular_system-iliacus_ID',
      'muscular_system-right_iliacus_ID',
      'muscular_system-left_iliacus_ID',
      'muscular_system-gluteus_maximus_ID',
      'muscular_system-right_gluteus_maximus_ID',
      'muscular_system-left_gluteus_maximus_ID',
      'muscular_system-gluteus_medius_ID',
      'muscular_system-right_gluteus_medius_ID',
      'muscular_system-left_gluteus_medius_ID',
      'muscular_system-gluteus_minimus_ID',
      'muscular_system-right_gluteus_minimus_ID',
      'muscular_system-left_gluteus_minimus_ID',
      'muscular_system-piriformis_ID',
      'muscular_system-right_piriformis_ID',
      'muscular_system-left_piriformis_ID',
      'muscular_system-obturator_internus_ID',
      'muscular_system-right_obturator_internus_ID',
      'muscular_system-left_obturator_internus_ID',
      'muscular_system-quadratus_femoris_ID',
      'muscular_system-right_quadratus_femoris_ID',
      'muscular_system-left_quadratus_femoris_ID',
      'connective_tissue-pelvic_floor_ID',
      'connective_tissue-right_inguinal_ligament_ID',
      'connective_tissue-left_inguinal_ligament_ID',
      'connective_tissue-sacrotuberous_ligament_ID',
      'connective_tissue-right_sacrospinous_ligament_ID',
      'connective_tissue-left_sacrospinous_ligament_ID',
    ],
    keywords: ['pelvis', 'hip', 'iliac'],
  },
  frontRightUpperLeg: {
    name: 'Front Right Upper Leg',
    ids: [
      'muscular_system-right_rectus_femoris_ID',
      'muscular_system-right_vastus_medialis_ID',
      'muscular_system-right_vastus_lateralis_ID',
      'muscular_system-right_vastus_intermedius_ID',
      'muscular_system-right_sartorius_ID',
      'muscular_system-right_articularis_genus_ID',
      'connective_tissue-right_quadriceps_tendon_ID',
      'muscular_system-right_pectineus_ID',
      'muscular_system-right_adductor_longus_ID',
      'muscular_system-right_gracilis_ID',
      'muscular_system-right_adductor_magnus_ID',
      'muscular_system-right_adductor_brevis_ID',
    ],
    keywords: ['right quadriceps', 'right femur anterior'],
  },
  backRightUpperLeg: {
    name: 'Back Right Upper Leg',
    ids: [
      'skeletal_system-right_femur_ID',
      'muscular_system-right_biceps_femoris_ID',
      'muscular_system-right_semimembranosus_ID',
      'muscular_system-right_semitendinosus_ID',
      'connective_tissue-right_ischial_tuberosity_tendon_ID',
      'muscular_system-right_iliotibial_tract_ID',
    ],
    keywords: ['right hamstring', 'right femur posterior'],
  },
  frontLeftUpperLeg: {
    name: 'Front Left Upper Leg',
    ids: [
      'muscular_system-left_rectus_femoris_ID',
      'muscular_system-left_vastus_medialis_ID',
      'muscular_system-left_vastus_lateralis_ID',
      'muscular_system-left_vastus_intermedius_ID',
      'muscular_system-left_sartorius_ID',
      'muscular_system-left_articularis_genus_ID',
      'connective_tissue-left_quadriceps_tendon_ID',
      'muscular_system-left_pectineus_ID',
      'muscular_system-left_adductor_longus_ID',
      'muscular_system-left_gracilis_ID',
      'muscular_system-left_adductor_magnus_ID',
      'muscular_system-left_adductor_brevis_ID',
    ],
    keywords: ['left quadriceps', 'left femur anterior'],
  },
  backLeftUpperLeg: {
    name: 'Back Left Upper Leg',
    ids: [
      'skeletal_system-left_femur_ID',
      'muscular_system-left_biceps_femoris_ID',
      'muscular_system-left_semimembranosus_ID',
      'muscular_system-left_semitendinosus_ID',
      'connective_tissue-left_ischial_tuberosity_tendon_ID',
      'muscular_system-left_iliotibial_tract_ID',
    ],
    keywords: ['left hamstring', 'left femur posterior'],
  },
  leftKnee: {
    name: 'Left Knee',
    ids: [
      'connective_tissue-left_patellar_ligament_ID',
      'skeletal_system-left_patella_ID',
      'skeletal_system-left_tibial_plateau_ID',
      'skeletal_system-left_femoral_condyles_ID',
      'connective_tissue-left_anterior_cruciate_ligament_ID',
      'connective_tissue-left_posterior_cruciate_ligament_ID',
      'connective_tissue-left_medial_collateral_ligament_ID',
      'connective_tissue-left_lateral_collateral_ligament_ID',
      'connective_tissue-left_meniscus_medial_ID',
      'connective_tissue-left_meniscus_lateral_ID',
      'connective_tissue-left_joint_capsule_ID',
      'connective_tissue-left_prepatellar_bursa_ID',
      'connective_tissue-left_infrapatellar_bursa_ID',
      'connective_tissue-left_subcutaneous_prepatellar_bursa_ID',
      'connective_tissue-left_subcutaneous_infrapatellar_bursa_ID',
      'connective_tissue-left_iliotibial_tract_bursa_ID',
      'connective_tissue-left_oblique_popliteal_ligament_ID',
      'connective_tissue-left_anserine_bursa_ID',
      'connective_tissue-fibrous_joint_capsule_of_left_knee_ID',
    ],
    keywords: ['left knee', 'left patella'],
  },
  rightKnee: {
    name: 'Right Knee',
    ids: [
      'skeletal_system-right_patella_ID',
      'skeletal_system-right_tibial_plateau_ID',
      'skeletal_system-right_femoral_condyles_ID',
      'connective_tissue-right_anterior_cruciate_ligament_ID',
      'connective_tissue-right_posterior_cruciate_ligament_ID',
      'connective_tissue-right_medial_collateral_ligament_ID',
      'connective_tissue-right_lateral_collateral_ligament_ID',
      'connective_tissue-right_meniscus_medial_ID',
      'connective_tissue-right_meniscus_lateral_ID',
      'connective_tissue-right_joint_capsule_ID',
      'connective_tissue-right_prepatellar_bursa_ID',
      'connective_tissue-right_infrapatellar_bursa_ID',
      'connective_tissue-right_suprapatellar_bursa_ID',
      'connective_tissue-right_patellar_ligament_ID',
      'connective_tissue-right_subcutaneous_prepatellar_bursa_ID',
      'connective_tissue-fibrous_joint_capsule_of_right_knee_ID',
      'connective_tissue-right_subcutaneous_infrapatellar_bursa_ID',
      'connective_tissue-right_iliotibial_tract_bursa_ID',
      'connective_tissue-right_oblique_popliteal_ligament_ID',
      'connective_tissue-right_anserine_bursa_ID',
    ],
    keywords: ['right knee', 'right patella'],
  },
  leftLowerLeg: {
    name: 'Left Lower Leg',
    ids: [
      'muscular_system-lateral_head_of_left_gastrocnemius_ID',
      'muscular_system-medial_head_of_left_gastrocnemius_ID',
      'skeletal_system-left_tibia_ID',
      'skeletal_system-left_fibula_ID',
      'muscular_system-left_tibialis_anterior_ID',
      'muscular_system-left_extensor_digitorum_longus_ID',
      'muscular_system-left_extensor_hallucis_longus_ID',
      'muscular_system-left_fibularis_longus_ID',
      'muscular_system-left_fibularis_brevis_ID',
      'muscular_system-left_gastrocnemius_ID',
      'muscular_system-left_soleus_ID',
      'muscular_system-left_plantaris_ID',
      'muscular_system-left_tibialis_posterior_ID',
      'muscular_system-left_flexor_digitorum_longus_ID',
      'muscular_system-left_flexor_hallucis_longus_ID',
      'muscular_system-left_popliteus_ID',
      'connective_tissue-left_crural_fascia_ID',
      'connective_tissue-left_interosseous_membrane_ID',
    ],
    keywords: ['left tibia', 'left fibula', 'left calf'],
  },
  rightLowerLeg: {
    name: 'Right Lower Leg',
    ids: [
      'muscular_system-lateral_head_of_right_gastrocnemius_ID',
      'muscular_system-medial_head_of_right_gastrocnemius_ID',
      'skeletal_system-right_tibia_ID',
      'skeletal_system-right_fibula_ID',
      'muscular_system-right_tibialis_anterior_ID',
      'muscular_system-right_extensor_digitorum_longus_ID',
      'muscular_system-right_extensor_hallucis_longus_ID',
      'muscular_system-right_fibularis_longus_ID',
      'muscular_system-right_fibularis_brevis_ID',
      'muscular_system-right_gastrocnemius_ID',
      'muscular_system-right_soleus_ID',
      'muscular_system-right_plantaris_ID',
      'muscular_system-right_tibialis_posterior_ID',
      'muscular_system-right_flexor_digitorum_longus_ID',
      'muscular_system-right_flexor_hallucis_longus_ID',
      'muscular_system-right_popliteus_ID',
      'connective_tissue-right_crural_fascia_ID',
      'connective_tissue-right_interosseous_membrane_ID',
    ],
    keywords: ['right tibia', 'right fibula', 'right calf'],
  },
  leftFoot: {
    name: 'Left Foot',
    ids: [
      'muscular_system-left_calcaneal_tendon_ID',
      'skeletal_system-left_calcaneus_ID',
      'skeletal_system-left_talus_ID',
      'skeletal_system-left_cuboid_ID',
      'skeletal_system-left_navicular_ID',
      'skeletal_system-left_medial_cuneiform_ID',
      'skeletal_system-left_intermediate_cuneiform_ID',
      'skeletal_system-left_lateral_cuneiform_ID',
      'skeletal_system-left_metatarsals_1-5_ID',
      'skeletal_system-left_phalanges_proximal_ID',
      'skeletal_system-left_phalanges_middle_ID',
      'skeletal_system-left_phalanges_distal_ID',
      'muscular_system-left_abductor_hallucis_ID',
      'muscular_system-left_flexor_digitorum_brevis_ID',
      'muscular_system-left_abductor_digiti_minimi_ID',
      'muscular_system-left_quadratus_plantae_ID',
      'muscular_system-left_lumbricals_of_foot_ID',
      'muscular_system-left_flexor_hallucis_brevis_ID',
      'muscular_system-left_adductor_hallucis_ID',
      'muscular_system-left_flexor_digiti_minimi_brevis_ID',
      'muscular_system-left_dorsal_interossei_ID',
      'muscular_system-left_plantar_interossei_ID',
      'connective_tissue-left_plantar_fascia_ID',
      'connective_tissue-left_achilles_tendon_insertion_ID',
      'connective_tissue-left_spring_ligament_ID',
      'connective_tissue-left_long_plantar_ligament_ID',
      'connective_tissue-left_short_plantar_ligament_ID',
    ],
    keywords: ['left foot', 'left ankle', 'left calcaneal', 'left achilles'],
  },
  rightFoot: {
    name: 'Right Foot',
    ids: [
      'muscular_system-right_calcaneal_tendon_ID',
      'skeletal_system-right_calcaneus_ID',
      'skeletal_system-right_talus_ID',
      'skeletal_system-right_cuboid_ID',
      'skeletal_system-right_navicular_ID',
      'skeletal_system-right_medial_cuneiform_ID',
      'skeletal_system-right_intermediate_cuneiform_ID',
      'skeletal_system-right_lateral_cuneiform_ID',
      'skeletal_system-right_first_metatarsal_ID',
      'skeletal_system-right_second_metatarsal_ID',
      'skeletal_system-right_third_metatarsal_ID',
      'skeletal_system-right_fourth_metatarsal_ID',
      'muscular_system-right_abductor_hallucis_ID',
      'muscular_system-right_flexor_digitorum_brevis_ID',
      'muscular_system-right_quadratus_plantae_ID',
      'muscular_system-right_extensor_hallucis_brevis_ID',
      'muscular_system-right_extensor_digitorum_brevis_ID',
      'connective_tissue-right_long_plantar_ligament_ID',
      'connective_tissue-right_short_plantar_ligament_ID',
      'connective_tissue-right_plantar_aponeurosis_ID',
      'connective_tissue-right_flexor_retinaculum_of_ankle_ID',
      'connective_tissue-right_dorsal_cuneonavicular_ligaments_ID',
    ],
    keywords: ['right foot', 'right ankle'],
  },
};
