export interface BodyPartGroup {
  name: string;
  ids: string[];
  keywords: string[];
}

export const bodyPartGroups: { [key: string]: BodyPartGroup } = {
  neck: {
    name: 'Neck',
    ids: [
      'muscular_system-sternocleidomastoid_ID',
      'muscular_system-right_sternocleidomastoid_ID',
      'muscular_system-left_sternocleidomastoid_ID',
      'muscular_system-platysma_ID',
      'muscular_system-right_platysma_ID',
      'muscular_system-left_platysma_ID',
      'muscular_system-anterior_scalene_ID',
      'muscular_system-right_anterior_scalene_ID',
      'muscular_system-left_anterior_scalene_ID',
      'muscular_system-middle_scalene_ID',
      'muscular_system-right_middle_scalene_ID',
      'muscular_system-left_middle_scalene_ID',
      'muscular_system-posterior_scalene_ID',
      'muscular_system-right_posterior_scalene_ID',
      'muscular_system-left_posterior_scalene_ID',
      'muscular_system-sternohyoid_ID',
      'muscular_system-right_sternohyoid_ID',
      'muscular_system-left_sternohyoid_ID',
      'muscular_system-omohyoid_ID',
      'muscular_system-right_superior_belly_of_omohyoid_ID',
      'muscular_system-left_superior_belly_of_omohyoid_ID',
      'muscular_system-right_inferior_belly_of_omohyoid_ID',
      'muscular_system-left_inferior_belly_of_omohyoid_ID',
      'muscular_system-thyrohyoid_ID',
      'muscular_system-right_thyrohyoid_ID',
      'muscular_system-left_thyrohyoid_ID',
      'muscular_system-sternothyroid_ID',
      'muscular_system-right_sternothyroid_ID',
      'muscular_system-left_sternothyroid_ID',
      'muscular_system-rectus_capitis_posterior_minor_ID',
      'muscular_system-right_rectus_capitis_posterior_minor_ID',
      'muscular_system-left_rectus_capitis_posterior_minor_ID',
      'muscular_system-rectus_capitis_posterior_major_ID',
      'muscular_system-right_rectus_capitis_posterior_major_ID',
      'muscular_system-left_rectus_capitis_posterior_major_ID',
      'muscular_system-obliquus_capitis_superior_ID',
      'muscular_system-right_obliquus_capitis_superior_ID',
      'muscular_system-left_obliquus_capitis_superior_ID',
      'muscular_system-obliquus_capitis_inferior_ID',
      'muscular_system-right_obliquus_capitis_inferior_ID',
      'muscular_system-left_obliquus_capitis_inferior_ID',
      'connective_tissue-anterior_longitudinal_ligament_ID',
      'connective_tissue-ligamentum_nuchae_ID',
      'muscular_system-left_splenius_capitis_ID',
      'muscular_system-right_splenius_capitis_ID',
    ],
    keywords: ['neck', 'cervical', 'throat', 'laryn', 'pharyn'],
  },
  leftShoulder: {
    name: 'Left Shoulder',
    ids: [
      'human_19_male_muscular_system-left_deltoid_ID',
      'human_19_male_muscular_system-left_teres_major_ID',
      'human_19_male_muscular_system-left_supraspinatus_ID',
      'human_19_male_muscular_system-left_infraspinatus_ID',
      'human_19_male_muscular_system-left_teres_minor_ID',
      'human_19_male_muscular_system-left_subscapularis_ID',
      'human_19_male_connective_tissue-left_acromioclavicular_ligament_ID',
      'human_19_male_connective_tissue-left_coracoacromial_ligament_ID',
      'human_19_male_connective_tissue-left_coracoclavicular_ligament_ID',
      'human_19_male_connective_tissue-left_glenohumeral_ligaments_ID',
    ],
    keywords: ['left shoulder', 'left deltoid'],
  },
  rightShoulder: {
    name: 'Right Shoulder',
    ids: [
      'human_19_male_muscular_system-right_deltoid_ID',
      'human_19_male_muscular_system-right_teres_major_ID',
      'human_19_male_muscular_system-right_supraspinatus_ID',
      'human_19_male_muscular_system-right_infraspinatus_ID',
      'human_19_male_muscular_system-right_teres_minor_ID',
      'human_19_male_muscular_system-right_subscapularis_ID',
      'human_19_male_connective_tissue-right_acromioclavicular_ligament_ID',
      'human_19_male_connective_tissue-right_coracoacromial_ligament_ID',
      'human_19_male_connective_tissue-right_coracoclavicular_ligament_ID',
      'human_19_male_connective_tissue-right_glenohumeral_ligaments_ID',
    ],
    keywords: ['right shoulder', 'right deltoid'],
  },
  leftUpperArm: {
    name: 'Left Upper Arm',
    ids: [
      'human_19_male_muscular_system-left_biceps_brachii_ID',
      'human_19_male_muscular_system-left_brachialis_ID',
      'human_19_male_muscular_system-left_triceps_brachii_ID',
      'human_19_male_muscular_system-left_coracobrachialis_ID',
      'human_19_male_connective_tissue-left_bicipital_aponeurosis_ID',
    ],
    keywords: ['left biceps', 'left triceps', 'left brachii'],
  },
  rightUpperArm: {
    name: 'Right Upper Arm',
    ids: [
      'human_19_male_muscular_system-right_biceps_brachii_ID',
      'human_19_male_muscular_system-right_brachialis_ID',
      'human_19_male_muscular_system-right_triceps_brachii_ID',
      'human_19_male_muscular_system-right_coracobrachialis_ID',
      'human_19_male_connective_tissue-right_bicipital_aponeurosis_ID',
    ],
    keywords: ['right biceps', 'right triceps', 'right brachii'],
  },
  leftElbow: {
    name: 'Left Elbow',
    ids: [
      'human_19_male_muscular_system-left_anconeus_ID',
      'human_19_male_connective_tissue-left_annular_ligament_ID',
      'human_19_male_connective_tissue-left_ulnar_collateral_ligament_ID',
      'human_19_male_connective_tissue-left_joint_capsule_ID',
      'human_19_male_connective_tissue-left_subcutaneous_olecranon_bursa_ID',
      'human_19_male_connective_tissue-left_elbow_joint_capsule_ID',
      'human_19_male_skeletal_system-left_humerus_ID',
      'human_19_male_skeletal_system-left_radius_ID',
      'human_19_male_connective_tissue-left_posterior_part_of_ulnar_collateral_ligament_ID',
      'human_19_male_muscular_system-left_bicipital_aponeurosis_ID',
    ],
    keywords: ['left elbow'],
  },
  rightElbow: {
    name: 'Right Elbow',
    ids: [
      'human_19_male_muscular_system-right_anconeus_ID',
      'human_19_male_connective_tissue-right_annular_ligament_ID',
      'human_19_male_connective_tissue-right_ulnar_collateral_ligament_ID',
      'human_19_male_connective_tissue-right_joint_capsule_ID',
      'human_19_male_connective_tissue-right_subcutaneous_olecranon_bursa_ID',
      'human_19_male_connective_tissue-right_elbow_joint_capsule_ID',
      'human_19_male_skeletal_system-right_humerus_ID',
      'human_19_male_skeletal_system-right_radius_ID',
      'human_19_male_connective_tissue-right_posterior_part_of_ulnar_collateral_ligament_ID',
      'human_19_male_muscular_system-right_bicipital_aponeurosis_ID',
    ],
    keywords: ['right elbow'],
  },
  leftForearmHand: {
    name: 'Left Forearm and Hand',
    ids: [
      'human_19_male_muscular_system-left_flexor_carpi_radialis_ID',
      'human_19_male_muscular_system-left_flexor_carpi_ulnaris_ID',
      'human_19_male_muscular_system-left_flexor_digitorum_superficialis_ID',
      'human_19_male_muscular_system-left_flexor_digitorum_profundus_ID',
      'human_19_male_muscular_system-left_flexor_pollicis_longus_ID',
      'human_19_male_muscular_system-left_palmaris_longus_ID',
      'human_19_male_muscular_system-left_pronator_teres_ID',
      'human_19_male_muscular_system-left_pronator_quadratus_ID',
      'human_19_male_muscular_system-left_extensor_carpi_radialis_longus_ID',
      'human_19_male_muscular_system-left_extensor_carpi_radialis_brevis_ID',
      'human_19_male_muscular_system-left_extensor_carpi_ulnaris_ID',
      'human_19_male_muscular_system-left_extensor_digitorum_ID',
      'human_19_male_muscular_system-left_extensor_digiti_minimi_ID',
      'human_19_male_muscular_system-left_extensor_indicis_ID',
      'human_19_male_muscular_system-left_extensor_pollicis_longus_ID',
      'human_19_male_muscular_system-left_extensor_pollicis_brevis_ID',
      'human_19_male_muscular_system-left_abductor_pollicis_longus_ID',
      'human_19_male_muscular_system-left_brachioradialis_ID',
      'human_19_male_muscular_system-left_abductor_pollicis_brevis_ID',
      'human_19_male_muscular_system-left_flexor_pollicis_brevis_ID',
      'human_19_male_muscular_system-left_adductor_pollicis_ID',
      'human_19_male_muscular_system-left_opponens_pollicis_ID',
      'human_19_male_muscular_system-left_abductor_digiti_minimi_ID',
      'human_19_male_muscular_system-left_flexor_digiti_minimi_brevis_of_hand_ID',
      'human_19_male_muscular_system-left_opponens_digiti_minimi_ID',
      'human_19_male_muscular_system-left_palmaris_brevis_ID',
      'human_19_male_muscular_system-first_lumbrical_muscle_of_left_hand_ID',
      'human_19_male_muscular_system-second_lumbrical_muscle_of_left_hand_ID',
      'human_19_male_muscular_system-third_lumbrical_muscle_of_left_hand_ID',
      'human_19_male_muscular_system-fourth_lumbrical_muscle_of_left_hand_ID',
      'human_19_male_muscular_system-first_palmar_interosseous_muscle_of_left_hand_ID',
      'human_19_male_muscular_system-second_palmar_interosseous_muscle_of_left_hand_ID',
      'human_19_male_muscular_system-third_palmar_interosseous_muscle_of_left_hand_ID',
      'human_19_male_muscular_system-first_dorsal_interosseous_muscle_of_left_hand_ID',
      'human_19_male_muscular_system-second_dorsal_interosseous_muscle_of_left_hand_ID',
      'human_19_male_muscular_system-third_dorsal_interosseous_muscle_of_left_hand_ID',
      'human_19_male_muscular_system-fourth_dorsal_interosseous_muscle_of_left_hand_ID',
      'human_19_male_connective_tissue-left_palmar_aponeurosis_ID',
      'human_19_male_connective_tissue-left_extensor_retinaculum_ID',
      'human_19_male_connective_tissue-left_flexor_retinaculum_ID',
    ],
    keywords: ['left forearm', 'left hand', 'left wrist'],
  },
  rightForearmHand: {
    name: 'Right Forearm and Hand',
    ids: [
      'human_19_male_muscular_system-right_flexor_carpi_radialis_ID',
      'human_19_male_muscular_system-right_flexor_carpi_ulnaris_ID',
      'human_19_male_muscular_system-right_flexor_digitorum_superficialis_ID',
      'human_19_male_muscular_system-right_flexor_digitorum_profundus_ID',
      'human_19_male_muscular_system-right_flexor_pollicis_longus_ID',
      'human_19_male_muscular_system-right_palmaris_longus_ID',
      'human_19_male_muscular_system-right_pronator_teres_ID',
      'human_19_male_muscular_system-right_pronator_quadratus_ID',
      'human_19_male_muscular_system-right_extensor_carpi_radialis_longus_ID',
      'human_19_male_muscular_system-right_extensor_carpi_radialis_brevis_ID',
      'human_19_male_muscular_system-right_extensor_carpi_ulnaris_ID',
      'human_19_male_muscular_system-right_extensor_digitorum_ID',
      'human_19_male_muscular_system-right_extensor_digiti_minimi_ID',
      'human_19_male_muscular_system-right_extensor_indicis_ID',
      'human_19_male_muscular_system-right_extensor_pollicis_longus_ID',
      'human_19_male_muscular_system-right_extensor_pollicis_brevis_ID',
      'human_19_male_muscular_system-right_abductor_pollicis_longus_ID',
      'human_19_male_muscular_system-right_brachioradialis_ID',
      'human_19_male_muscular_system-right_abductor_pollicis_brevis_ID',
      'human_19_male_muscular_system-right_flexor_pollicis_brevis_ID',
      'human_19_male_muscular_system-right_adductor_pollicis_ID',
      'human_19_male_muscular_system-right_opponens_pollicis_ID',
      'human_19_male_muscular_system-right_abductor_digiti_minimi_ID',
      'human_19_male_muscular_system-right_flexor_digiti_minimi_brevis_of_hand_ID',
      'human_19_male_muscular_system-right_opponens_digiti_minimi_ID',
      'human_19_male_muscular_system-right_palmaris_brevis_ID',
      'human_19_male_muscular_system-first_lumbrical_muscle_of_right_hand_ID',
      'human_19_male_muscular_system-second_lumbrical_muscle_of_right_hand_ID',
      'human_19_male_muscular_system-third_lumbrical_muscle_of_right_hand_ID',
      'human_19_male_muscular_system-fourth_lumbrical_muscle_of_right_hand_ID',
      'human_19_male_muscular_system-first_palmar_interosseous_muscle_of_right_hand_ID',
      'human_19_male_muscular_system-second_palmar_interosseous_muscle_of_right_hand_ID',
      'human_19_male_muscular_system-third_palmar_interosseous_muscle_of_right_hand_ID',
      'human_19_male_muscular_system-first_dorsal_interosseous_muscle_of_right_hand_ID',
      'human_19_male_muscular_system-second_dorsal_interosseous_muscle_of_right_hand_ID',
      'human_19_male_muscular_system-third_dorsal_interosseous_muscle_of_right_hand_ID',
      'human_19_male_muscular_system-fourth_dorsal_interosseous_muscle_of_right_hand_ID',
      'human_19_male_connective_tissue-right_palmar_aponeurosis_ID',
      'human_19_male_connective_tissue-right_extensor_retinaculum_ID',
      'human_19_male_connective_tissue-right_flexor_retinaculum_ID',
    ],
    keywords: ['right forearm', 'right hand', 'right wrist'],
  },
  chest: {
    name: 'Chest',
    ids: [],
    keywords: ['pectoral', 'chest'],
  },
  torso: {
    name: 'Rest of Torso',
    ids: [],
    keywords: ['abdominal', 'sternum', 'rib', 'costal'],
  },
  upperBack: {
    name: 'Upper Back',
    ids: [
      'human_19_male_muscular_system-trapezius_ID',
      'human_19_male_muscular_system-right_trapezius_ID',
      'human_19_male_muscular_system-left_trapezius_ID',
      'human_19_male_muscular_system-rhomboid_major_ID',
      'human_19_male_muscular_system-right_rhomboid_major_ID',
      'human_19_male_muscular_system-left_rhomboid_major_ID',
      'human_19_male_muscular_system-rhomboid_minor_ID',
      'human_19_male_muscular_system-right_rhomboid_minor_ID',
      'human_19_male_muscular_system-left_rhomboid_minor_ID',
      'human_19_male_muscular_system-levator_scapulae_ID',
      'human_19_male_muscular_system-right_levator_scapulae_ID',
      'human_19_male_muscular_system-left_levator_scapulae_ID',
      'human_19_male_connective_tissue-ligamentum_nuchae_ID',
      'human_19_male_connective_tissue-thoracolumbar_fascia_upper_ID',
    ],
    keywords: ['upper back', 'trapezius', 'rhomboid'],
  },
  lowerBack: {
    name: 'Lower Back',
    ids: [
      'human_19_male_muscular_system-erector_spinae_ID',
      'human_19_male_muscular_system-right_erector_spinae_ID',
      'human_19_male_muscular_system-left_erector_spinae_ID',
      'human_19_male_muscular_system-quadratus_lumborum_ID',
      'human_19_male_muscular_system-right_quadratus_lumborum_ID',
      'human_19_male_muscular_system-left_quadratus_lumborum_ID',
      'human_19_male_muscular_system-multifidus_ID',
      'human_19_male_muscular_system-right_multifidus_ID',
      'human_19_male_muscular_system-left_multifidus_ID',
      'human_19_male_connective_tissue-thoracolumbar_fascia_lower_ID',
      'human_19_male_connective_tissue-anterior_longitudinal_ligament_lumbar_ID',
      'human_19_male_connective_tissue-posterior_longitudinal_ligament_lumbar_ID',
      'human_19_male_connective_tissue-ligamentum_flavum_lumbar_ID',
      'human_19_male_muscular_system-left_latissimus_dorsi_ID',
      'human_19_male_muscular_system-right_latissimus_dorsi_ID',
    ],
    keywords: ['lower back', 'lumbar'],
  },
  pelvisHip: {
    name: 'Pelvis & Hip Region',
    ids: [
      'human_19_male_muscular_system-iliopsoas_ID',
      'human_19_male_muscular_system-right_iliopsoas_ID',
      'human_19_male_muscular_system-left_iliopsoas_ID',
      'human_19_male_muscular_system-psoas_major_ID',
      'human_19_male_muscular_system-right_psoas_major_ID',
      'human_19_male_muscular_system-left_psoas_major_ID',
      'human_19_male_muscular_system-iliacus_ID',
      'human_19_male_muscular_system-right_iliacus_ID',
      'human_19_male_muscular_system-left_iliacus_ID',
      'human_19_male_muscular_system-gluteus_maximus_ID',
      'human_19_male_muscular_system-right_gluteus_maximus_ID',
      'human_19_male_muscular_system-left_gluteus_maximus_ID',
      'human_19_male_muscular_system-gluteus_medius_ID',
      'human_19_male_muscular_system-right_gluteus_medius_ID',
      'human_19_male_muscular_system-left_gluteus_medius_ID',
      'human_19_male_muscular_system-gluteus_minimus_ID',
      'human_19_male_muscular_system-right_gluteus_minimus_ID',
      'human_19_male_muscular_system-left_gluteus_minimus_ID',
      'human_19_male_muscular_system-piriformis_ID',
      'human_19_male_muscular_system-right_piriformis_ID',
      'human_19_male_muscular_system-left_piriformis_ID',
      'human_19_male_muscular_system-obturator_internus_ID',
      'human_19_male_muscular_system-right_obturator_internus_ID',
      'human_19_male_muscular_system-left_obturator_internus_ID',
      'human_19_male_muscular_system-quadratus_femoris_ID',
      'human_19_male_muscular_system-right_quadratus_femoris_ID',
      'human_19_male_muscular_system-left_quadratus_femoris_ID',
      'human_19_male_connective_tissue-pelvic_floor_ID',
      'human_19_male_connective_tissue-right_inguinal_ligament_ID',
      'human_19_male_connective_tissue-left_inguinal_ligament_ID',
      'human_19_male_connective_tissue-sacrotuberous_ligament_ID',
      'human_19_male_connective_tissue-right_sacrospinous_ligament_ID',
      'human_19_male_connective_tissue-left_sacrospinous_ligament_ID',
    ],
    keywords: ['pelvis', 'hip', 'iliac'],
  },
  frontRightUpperLeg: {
    name: 'Front Right Upper Leg',
    ids: [],
    keywords: ['right quadriceps', 'right femur anterior'],
  },
  backRightUpperLeg: {
    name: 'Back Right Upper Leg',
    ids: [],
    keywords: ['right hamstring', 'right femur posterior'],
  },
  frontLeftUpperLeg: {
    name: 'Front Left Upper Leg',
    ids: [],
    keywords: ['left quadriceps', 'left femur anterior'],
  },
  backLeftUpperLeg: {
    name: 'Back Left Upper Leg',
    ids: [],
    keywords: ['left hamstring', 'left femur posterior'],
  },
  leftKnee: {
    name: 'Left Knee',
    ids: [],
    keywords: ['left knee', 'left patella'],
  },
  rightKnee: {
    name: 'Right Knee',
    ids: [],
    keywords: ['right knee', 'right patella'],
  },
  leftLowerLeg: {
    name: 'Left Lower Leg',
    ids: [],
    keywords: ['left tibia', 'left fibula', 'left calf'],
  },
  rightLowerLeg: {
    name: 'Right Lower Leg',
    ids: [],
    keywords: ['right tibia', 'right fibula', 'right calf'],
  },
  leftFoot: {
    name: 'Left Foot',
    ids: [],
    keywords: ['left foot', 'left ankle'],
  },
  rightFoot: {
    name: 'Right Foot',
    ids: [],
    keywords: ['right foot', 'right ankle'],
  },
};
